### ISSUE TITLE
How to know when the network is idle (not on loading)

### ISSUE THREAD

**Issue by eduardosada** [GoogleChromeLabs/puppeteer-examples#24]
Hi @ebidel 

Could you tell me why is this line commented?

https://github.com/GoogleChromeLabs/puppeteer-examples/blob/59355609ecb3c2e396a289b28f34d5116fc89b8e/lazyimages_without_scroll_events.js#L97

I would like to know if it's possible to know when the network is idle.

**Comment by ebidel** [comment]
I think I was experimenting. `await page.goto(url, {waitUntil: 'networkidle2'});` should wait for the page to load and network to be idle. For this script, I was seeing some resources lazy loaded well after the page navigation was complete. I wanted to catch those too, hence the additional `page.waitFor` after the `page.goto`.
