### ISSUE TITLE
crawl site missing 'output' folder

### ISSUE THREAD

**Issue by mboeser** [GoogleChromeLabs/puppeteer-examples#6]
I received the error below. I could verify the script was trying to mkdir, but it wouldn't work. After manually creating the folder 'output'. The script worked as expected. Unsure if this is a bug or user error...

`UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, mkdir 'output/https___news.polymer-project.org_'`

**Comment by ebidel** [comment]
The script should probably so this for you. Feel free to submit a PR.
